blank_issues_enabled: false
contact_links:
  - name: 📃 Build CherishOS
    url: https://github.com/CherishOS/android_manifest/
    about: See initial CherishOS build documentation
  - name: 🗨 Telegram
    url: https://t.me/CherishOS
    about: Join the chat on Telegram